import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="bg-blue-400 h-[70px] flex justify-between items-center">
      <Link href="" className="text-2xl text-white font-semibold ml-[80px]">Jalal Khan</Link>
      <div className="flex gap-6 mr-5">
        <Link className="hover:text-blue-50 duration-300" href="/home">Home</Link>
        <Link className="hover:text-blue-50 duration-300" href="/about">About</Link>
        <Link className="hover:text-blue-50 duration-300" href="/blogs">Blogs</Link>
        <Link className="hover:text-blue-50 duration-300" href="/contact">Contact</Link>
      </div>
      </nav>
        {children}</body>
    </html>
  );
}
